language: groovy
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
jdk:
- oraclejdk8
install: true
script: "./travis-build.sh"
